name: Snapshot Release on Comment

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  snapshot:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '!snapshot')
    name: Create Snapshot Release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      issues: write
      pull-requests: write

    steps:
      - name: Get PR Info
        uses: xt0rted/pull-request-comment-branch@v3
        id: pr_info
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: ${{ steps.pr_info.outputs.head_ref }}
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm build

      - name: Force Patch Snapshot Changeset
        run: |
          echo "Clearing existing changesets to force patch snapshot..."
          find .changeset -name "*.md" ! -name "README.md" -delete

          echo "Creating temporary patch changeset."

          cat <<EOF > .changeset/temp-snapshot.md
          ---
          '@monocloud/management-core': patch
          '@monocloud/management': patch
          ---

          Snapshot release.
          EOF

      - name: Create Snapshot Version
        run: pnpm changeset version --snapshot canary

      - name: Add Credentials to .npmrc
        run: |
          echo "@monocloud:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
        shell: bash

      - name: Publish NPM Packages as Canary
        run: |
          pnpm changeset publish --tag canary --no-git-tag

      - name: Comment on PR with version
        uses: actions/github-script@v8
        with:
          script: |
            const packageJson = require('./package.json');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ðŸš€ Private Snapshot published! \nVersion: \`${packageJson.version}\``
            })
